variables:
  CI_APPLICATION_REPOSITORY: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG
  CI_APPLICATION_TAG: $CI_COMMIT_SHA
  GIT_SUBMODULE_STRATEGY: recursive
stages:  
  - build
  # - test
  # - deploy

build:
  tags:
    - shell

  # Use the official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -f ./Dockerfile -t $CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG -t $CI_APPLICATION_REPOSITORY:latest .
    - docker push $CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG
    - docker push $CI_APPLICATION_REPOSITORY:latest

deploy:
  tags:
    - shell

  # Use the official docker image.
  image: docker:latest
  stage: build
  script:
    - whoami
    - pwd

# test-back:
#   # Use the official docker image.
#   image: $CI_APPLICATION_REPOSITORY:back-$CI_APPLICATION_TAG
#   stage: test
#   script:
#     - cd /app
#     - npm run test


# deploy:
#   # Use the official docker image.
#   image: "registry.gitlab.com/gitlab-org/cluster-integration/auto-deploy-image:v2.6.0"
#   stage: deploy
#   script:
#     - apk add --update coreutils
#     - echo "$KUBE_CLUSTER_CERTIFICATE" | base64 --decode > cert.crt
#   # backend
#     - kubectl --kubeconfig="/dev/null" --server=$KUBE_SERVER_URL --token=$KUBE_TOKEN --certificate-authority=cert.crt -n birdie set image deployments/nodejs-backend backend=$CI_APPLICATION_REPOSITORY:back-$CI_APPLICATION_TAG
#   # frontend
#     - kubectl --kubeconfig="/dev/null" --server=$KUBE_SERVER_URL --token=$KUBE_TOKEN --certificate-authority=cert.crt -n birdie set image deployments/nodejs-frontend frontend=$CI_APPLICATION_REPOSITORY:front-$CI_APPLICATION_TAG
#   only:
#     refs:
#       - main

